### ISSUE TITLE
PDFLatex not found from Flatpak installed from Fedora Flatpak Registry

### ISSUE THREAD

**Issue by lunarlettuce** [xournalpp/xournalpp#5524]
### Operating System

Linux

### (Linux only) Distribution

Fedora Silverblue

### (Linux only) Desktop Environment

GNOME

### (Linux Only) Display Server

Wayland

### Installation Method

Fedora Flatpak Registry

### Xournal++ Version

1.2.2

### libgtk Version

3.24.41

### Bug Description

When clicking on the "Add/edit Tex" button, a message shows that pdflatex is missing, even though org.freedesktop.Sdk.Extension.texlive//23.08 is installed. 

### Expected Behaviour

Latex features are available for use.

### Steps to Reproduce

1. Press add/edit Tex button

### Additional Context

This flatpak was not installed from Flathub, but from Fedora Flatpak Registry. I have tried copying the ENV variables from Flathub using Flatseal, but to no avail.

**Comment by rolandlo** [comment]
I didn't even know that there is a xournalpp flatpak in the Fedora Flatpak Registry. The [manifest](https://src.fedoraproject.org/flatpaks/xournalpp/blob/stable/f/container.yaml) doesn't add the texlive extension (via
```yaml
add-extensions:
  org.freedesktop.Sdk.Extension.texlive:
    directory: extensions
    subdirectories: true
    no-autodownload: true
    autodelete: true
    version: '23.08'
```
), so it can't access that extension even when it is installed.

It's an issue that should be raised at the Fedora Flatpak Registry. We can't do anything about it here.
